name: bytes_cloud
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: '>=0.11.3+12'
  path_provider: ^0.4.1
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+1
flutter:
  uses-material-design: true
  assets:
    - images/logo.png


