name: bytes_cloud
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: '>=0.11.3+12'
  path_provider: ^0.4.1
  shared_preferences: ^0.5.3+1
  permission_handler: ^4.2.0+hotfix.3
  intl: ^0.16.0
  fluttertoast: ^3.1.3
  table_calendar: ^2.2.2
  event_bus: ^1.1.0
  flutter_staggered_grid_view: ^0.2.7
  flutter_spinkit: ^4.1.1 #进度条
  flutter_markdown: ^0.3.3
  provider: ^4.0.4
  sqflite: ^1.2.0
  dio: 3.0.9 #latest version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    # 不要包含中文
    - assets/images/folder.png
    - assets/images/image.png
    - assets/images/ppt.png
    - assets/images/word.png
    - assets/images/excel.png
    - assets/images/txt.png
    - assets/images/file.png
    - assets/images/zip.png
    - assets/images/mp3.png
    - assets/images/video.png
    - assets/images/psd.png
    - assets/images/unknown.png
    - assets/images/photo.png
    - assets/images/audio.png
    - assets/images/audio2.png
    - assets/images/scan.png
    - assets/images/file2.png
    - assets/images/folder2.png
    - assets/images/doc.png
    - assets/images/note.png
    - assets/images/group.png
    - assets/images/mark.png
    - assets/images/setting.png
    - assets/images/share.png
    - assets/images/trash.png
    - assets/images/faceback.png
    - assets/images/downloaded.png
    - assets/images/change_user.png


