name: bytes_cloud
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: '>=0.11.3+12'
  path_provider: ^1.6.5
  shared_preferences: ^0.5.3+1
  permission_handler: ^4.2.0+hotfix.3
  intl: ^0.16.0
  fluttertoast: ^3.1.3
  event_bus: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_markdown: ^0.3.3
  provider: ^4.0.4
  sqflite: ^1.2.0
  dio: 3.0.9 #latest version
  dio_cookie_manager: 1.0.0
  cookie_jar: ^1.0.0

  image_picker: ^0.6.3+4
  multi_image_picker: ^4.6.2
  extended_image: ^0.7.1  # 图片查看器
  open_file: ^3.0.1 # https://pub.dev/packages/open_file#-readme-tab-

  # wflutter_filereader: ^2.0.0 # 文件阅读器 failed in android 10
  # ios add <key>io.flutter.embedded_views_preview</key><true/>
  # zefyr: ^0.10.0
  # native_pdf_view: 2.2.0

  flutter_fullpdfview: ^1.0.3+2
  video_player: ^0.10.8+1
  thumbnails: ^1.0.1 # 视频缩略图
  barcode_scan: ^2.0.1 # 二维码
  flutter_qr_reader: ^1.0.3
  qr_flutter: ^3.2.0  # 生成二维码

  font_awesome_flutter: ^8.8.0 #Flutter的图标库
  image_gallery_saver: ^1.2.2 #保存照片
  fluwx: ^2.0.8+1 # 微信分享
  url_launcher: ^5.4.5 # 发邮件、打电话
  easy_contact_picker: ^0.0.2 # 获取通讯录





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts :
    - family : NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
        - asset: assets/fonts/NotoSansSC-Bold.otf
          weight: 700

  assets:
    # 不要包含中文
    - assets/images/folder.png
    - assets/images/image.png
    - assets/images/ppt.png
    - assets/images/word.png
    - assets/images/excel.png
    - assets/images/txt.png
    - assets/images/file.png
    - assets/images/compress_file.png
    - assets/images/music.png
    - assets/images/video.png
    - assets/images/psd.png
    - assets/images/unknown.png
    - assets/images/photo.png
    - assets/images/audio.png
    - assets/images/audio2.png
    - assets/images/scan.png
    - assets/images/file2.png
    - assets/images/folder2.png
    - assets/images/doc.png
    - assets/images/note.png
    - assets/images/group.png
    - assets/images/mark.png
    - assets/images/setting.png
    - assets/images/share.png
    - assets/images/trash.png
    - assets/images/faceback.png
    - assets/images/download.png
    - assets/images/change_user.png
    - assets/images/QQ.png
    - assets/images/wechat.png
    - assets/images/null.png
    - assets/images/3gp.png
    - assets/images/aac.png
    - assets/images/avi.png
    - assets/images/flv.png
    - assets/images/mp3.png
    - assets/images/mp4.png
    - assets/images/wav.png
    - assets/images/rar.png
    - assets/images/zip.png
    - assets/images/7z.png
    - assets/images/flac.png
    - assets/images/phone.png
    - assets/images/screamshot.png
    - assets/images/camera.png
    - assets/images/back.png
    - assets/images/night.png
    - assets/images/delete.png
    - assets/images/modify.png
    - assets/images/more.png
    - assets/images/move.png
    - assets/images/share2.png
    - assets/images/login_bg.jpeg
    - assets/images/avator.jpg
    - assets/images/qrcode.png
    - assets/images/link.png











